# CSE 413: Simulation and Modeling Lab
**Lab Performance 02: Unique Matrix Value Investigation**  
**Course Instructor:** Afroja Ahmed Smrity  
**Student Name:** Azhar  
**Student ID:** 1120  

## 1. Create Personal Matrix A

In [5]:
import numpy as np

# Student ID: 1120
d1 = 0  # last digit
d2 = 2  # second last digit

A = np.array([
    [d1 + 2, d2 + 1],
    [2 * d1, d2 + 2]
], dtype=float)

print("Matrix A:")
print(A)

Matrix A:
[[2. 3.]
 [0. 4.]]


## 2. Analyze Matrix A

In [6]:
shape_A = A.shape
det_A = np.linalg.det(A)
rank_A = np.linalg.matrix_rank(A)
eigenvals_A = np.linalg.eigvals(A)

print(f"Shape: {shape_A}")
print(f"Determinant: {det_A:.2f}")
print(f"Rank: {rank_A}")
print(f"Eigenvalues: {eigenvals_A}")

if det_A != 0:
    inv_A = np.linalg.inv(A)
    print("Inverse of A:")
    print(inv_A)
else:
    print("Matrix A is singular (no inverse).")

Shape: (2, 2)
Determinant: 8.00
Rank: 2
Eigenvalues: [2. 4.]
Inverse of A:
[[ 0.5   -0.375]
 [ 0.     0.25 ]]


## 3. Value Change Experiment

In [10]:
# copy A and change element at row 1, col 0 (+1)
B = A.copy()
B[1, 0] += 1

print("Changed element at index (1, 0) from 0.0 to 1.0")
print("Matrix B:")
print(B)

Changed element at index (1, 0) from 0.0 to 1.0
Matrix B:
[[2. 3.]
 [1. 4.]]


## 4. Re-analyze Matrix B

In [8]:
shape_B = B.shape
det_B = np.linalg.det(B)
rank_B = np.linalg.matrix_rank(B)
eigenvals_B = np.linalg.eigvals(B)

print(f"Shape: {shape_B}")
print(f"Determinant: {det_B:.2f}")
print(f"Rank: {rank_B}")
print(f"Eigenvalues: {eigenvals_B}")

if det_B != 0:
    inv_B = np.linalg.inv(B)
    print("Inverse of B:")
    print(inv_B)
else:
    print("Matrix B is singular (no inverse).")

Shape: (2, 2)
Determinant: 5.00
Rank: 2
Eigenvalues: [1. 5.]
Inverse of B:
[[ 0.8 -0.6]
 [-0.2  0.4]]


## 5. Comparison & Explanation

### 1. Determinant Change
- **Matrix A Det:** 8.00  
- **Matrix B Det:** 5.00  
- **Explanation:** Determinant decreased from 8 to 5. For a 2x2 matrix $\begin{bmatrix} a & b \\ c & d \end{bmatrix}$, $\det = ad - bc$. In A, $c=0$ so det was $2 \times 4 = 8$. Changing $c$ to $1$ introduced the off-diagonal product $bc = 3 \times 1 = 3$, reducing the determinant by 3.

### 2. Rank Analysis
- **Matrix A Rank:** 2  
- **Matrix B Rank:** 2  
- **Explanation:** The rank did not change. Since both determinants are non-zero ($\det(A)=8 \neq 0$, $\det(B)=5 \neq 0$), both matrices are full rank ($2 \times 2$) with linearly independent rows.

### 3. Eigenvalues Response
- **Matrix A Eigenvalues:** [2.0, 4.0]  
- **Matrix B Eigenvalues:** [1.0, 5.0]  
- **Explanation:** Matrix A is upper triangular, so its eigenvalues were its diagonal entries (2 and 4). Modifying the off-diagonal element $B_{1,0}$ coupled the rows, spreading the eigenvalues further apart to 1 and 5 while preserving the matrix trace ($2+4 = 1+5 = 6$).

### 4. Invertibility Comparison
- **Explanation:** Matrix B is harder to invert than Matrix A. Matrix A is upper triangular, allowing fast inversion via back-substitution without computing off-diagonal cofactors. Matrix B is a full non-triangular matrix, requiring full elimination steps and yielding non-integer fractional values.