---
## 1. Advanced Scalar & Array Operations


In [2]:
import numpy as np

scalar = 4.1
arr_1d = np.array([-0.9, -0.4, 0.0, 0.25, 0.6, 0.85, 1.5, 3.2], dtype=np.float64)

print("Scalar value:", scalar)
print("Original 1D Array:", arr_1d)


ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.

In [ ]:
# Arithmetic Operations
print("--- Arithmetic Operations ---")
print("Addition with scalar (arr + scalar):\n", arr_1d + scalar)
print("\nSubtraction with scalar (arr - scalar):\n", arr_1d - scalar)
print("\nMultiplication with scalar (arr * scalar):\n", arr_1d * scalar)
print("\nDivision with scalar (arr / scalar):\n", arr_1d / scalar)

#pwer with bases
power_result = np.power(np.abs(arr_1d), scalar)
print("\nPower operation (|arr|^scalar):\n", power_result)


--- Arithmetic Operations ---
Addition with scalar (arr + scalar):
 [3.2  3.7  4.1  4.35 4.7  4.95 5.6  7.3 ]

Subtraction with scalar (arr - scalar):
 [-5.   -4.5  -4.1  -3.85 -3.5  -3.25 -2.6  -0.9 ]

Multiplication with scalar (arr * scalar):
 [-3.69  -1.64   0.     1.025  2.46   3.485  6.15  13.12 ]

Division with scalar (arr / scalar):
 [-0.2195122  -0.09756098  0.          0.06097561  0.14634146  0.20731707
  0.36585366  0.7804878 ]

Power operation (|arr|^scalar):
 [6.49223585e-01 2.33585545e-02 0.00000000e+00 3.40058814e-03
 1.23145948e-01 5.13591226e-01 5.27198495e+00 1.17791760e+02]


In [ ]:
print("--- Mathematical Functions ---")

abs_val = np.abs(arr_1d)
print("Absolute Value (np.abs):\n", abs_val)

sqrt_val = np.sqrt(np.abs(arr_1d))
print("\nSquare Root (np.sqrt of absolute values):\n", sqrt_val)

# exponential function
exp_val = np.exp(arr_1d)
print("\nExponential Function (np.exp):\n", exp_val)

# natural flogarithm 
log_val = np.log(np.abs(arr_1d) + 1e-10)
print("\nNatural Logarithm (np.log):\n", log_val)

#log base 10
log10_val = np.log10(np.abs(arr_1d) + 1e-10)
print("\nLogarithm Base 10 (np.log10):\n", log10_val)


--- Mathematical Functions ---
Absolute Value (np.abs):
 [0.9  0.4  0.   0.25 0.6  0.85 1.5  3.2 ]

Square Root (np.sqrt of absolute values):
 [0.9486833  0.63245553 0.         0.5        0.77459667 0.92195445
 1.22474487 1.78885438]

Exponential Function (np.exp):
 [ 0.40656966  0.67032005  1.          1.28402542  1.8221188   2.33964685
  4.48168907 24.5325302 ]

Natural Logarithm (np.log):
 [ -0.10536052  -0.91629073 -23.02585093  -1.38629436  -0.51082562
  -0.16251893   0.40546511   1.16315081]

Logarithm Base 10 (np.log10):
 [ -0.04575749  -0.39794001 -10.          -0.60205999  -0.22184875
  -0.07058107   0.17609126   0.50514998]


In [ ]:
# trigonometric Functions
print("--- Trigonometric Functions ---")
print("sin():\n", np.sin(arr_1d))
print("\ncos():\n", np.cos(arr_1d))
print("\ntan():\n", np.tan(arr_1d))

arr_clipped = np.clip(arr_1d, -1.0, 1.0)
print("\nClipped Array for Inverse Trig (-1 to 1):\n", arr_clipped)

print("\narcsin():\n", np.arcsin(arr_clipped))
print("\narccos():\n", np.arccos(arr_clipped))
print("\narctan():\n", np.arctan(arr_1d))


--- Trigonometric Functions ---
sin():
 [-0.78332691 -0.38941834  0.          0.24740396  0.56464247  0.75128041
  0.99749499 -0.05837414]

cos():
 [ 0.62160997  0.92106099  1.          0.96891242  0.82533561  0.65998315
  0.0707372  -0.99829478]

tan():
 [-1.26015822 -0.42279322  0.          0.25534192  0.68413681  1.13833271
 14.10141995  0.05847385]

Clipped Array for Inverse Trig (-1 to 1):
 [-0.9  -0.4   0.    0.25  0.6   0.85  1.    1.  ]

arcsin():
 [-1.11976951 -0.41151685  0.          0.25268026  0.64350111  1.01598529
  1.57079633  1.57079633]

arccos():
 [2.69056584 1.98231317 1.57079633 1.31811607 0.92729522 0.55481103
 0.         0.        ]

arctan():
 [-0.7328151  -0.38050638  0.          0.24497866  0.5404195   0.70449406
  0.98279372  1.26791146]


---
## 2. Matrix Mathematical Operations


In [ ]:

matrix_4x3 = np.array([
    [-1.25,  0.50,  2.10],
    [-0.75, -2.80,  0.00],
    [ 0.35,  1.20, -0.95],
    [ 3.50, -1.10,  0.80]
], dtype=np.float64)

print("Custom 4x3 Matrix:\n", matrix_4x3)
print("Matrix Shape:", matrix_4x3.shape)


Custom 4x3 Matrix:
 [[-1.25  0.5   2.1 ]
 [-0.75 -2.8   0.  ]
 [ 0.35  1.2  -0.95]
 [ 3.5  -1.1   0.8 ]]
Matrix Shape: (4, 3)


In [ ]:
# Exponential & Logarithmic Operations
print("--- Exponential & Logarithmic Operations ---")
print("exp():\n", np.exp(matrix_4x3))

# Handling negative values properly using np.abs() and epsilon offset
print("\nlog() (Natural Logarithm of absolute values):\n", np.log(np.abs(matrix_4x3) + 1e-10))
print("\nlog10() (Logarithm Base 10 of absolute values):\n", np.log10(np.abs(matrix_4x3) + 1e-10))


--- Exponential & Logarithmic Operations ---
exp():
 [[ 0.2865048   1.64872127  8.16616991]
 [ 0.47236655  0.06081006  1.        ]
 [ 1.41906755  3.32011692  0.38674102]
 [33.11545196  0.33287108  2.22554093]]

log() (Natural Logarithm of absolute values):
 [[  0.22314355  -0.69314718   0.74193734]
 [ -0.28768207   1.02961942 -23.02585093]
 [ -1.04982212   0.18232156  -0.05129329]
 [  1.25276297   0.09531018  -0.22314355]]

log10() (Logarithm Base 10 of absolute values):
 [[  0.09691001  -0.30103      0.32221929]
 [ -0.12493874   0.44715803 -10.        ]
 [ -0.45593196   0.07918125  -0.02227639]
 [  0.54406804   0.04139269  -0.09691001]]


In [ ]:
# Other Mathematical Operations
print("--- Other Mathematical Operations ---")
print("Absolute Value:\n", np.abs(matrix_4x3))
print("\nSquare Root (of absolute values):\n", np.sqrt(np.abs(matrix_4x3)))
print("\nSquare:\n", np.square(matrix_4x3))
print("\nCube Root (handles negatives natively):\n", np.cbrt(matrix_4x3))

print("\n--- Rounding and Remainder Operations ---")
print("Remainder when divided by 3 (matrix % 3):\n", np.fmod(matrix_4x3, 3))
print("\nround():\n", np.round(matrix_4x3))
print("\nfloor():\n", np.floor(matrix_4x3))
print("\nceil():\n", np.ceil(matrix_4x3))


--- Other Mathematical Operations ---
Absolute Value:
 [[1.25 0.5  2.1 ]
 [0.75 2.8  0.  ]
 [0.35 1.2  0.95]
 [3.5  1.1  0.8 ]]

Square Root (of absolute values):
 [[1.11803399 0.70710678 1.44913767]
 [0.8660254  1.67332005 0.        ]
 [0.59160798 1.09544512 0.97467943]
 [1.87082869 1.04880885 0.89442719]]

Square:
 [[ 1.5625  0.25    4.41  ]
 [ 0.5625  7.84    0.    ]
 [ 0.1225  1.44    0.9025]
 [12.25    1.21    0.64  ]]

Cube Root (handles negatives natively):
 [[-1.07721735  0.79370053  1.28057916]
 [-0.9085603  -1.40945975  0.        ]
 [ 0.70472987  1.06265857 -0.98304757]
 [ 1.51829449 -1.03228012  0.92831777]]

--- Rounding and Remainder Operations ---
Remainder when divided by 3 (matrix % 3):
 [[-1.25  0.5   2.1 ]
 [-0.75 -2.8   0.  ]
 [ 0.35  1.2  -0.95]
 [ 0.5  -1.1   0.8 ]]

round():
 [[-1.  0.  2.]
 [-1. -3.  0.]
 [ 0.  1. -1.]
 [ 4. -1.  1.]]

floor():
 [[-2.  0.  2.]
 [-1. -3.  0.]
 [ 0.  1. -1.]
 [ 3. -2.  0.]]

ceil():
 [[-1.  1.  3.]
 [-0. -2.  0.]
 [ 1.  2. -0.]
 [ 

---
## 3. Matrix Statistics and Analysis


In [ ]:
# Create a 3x4 matrix with random floating-point values
np.random.seed(42)  # Set seed for reproducible results
matrix_3x4 = np.random.uniform(-10, 10, (3, 4))

print("Random 3x4 Matrix:\n", matrix_3x4)


Random 3x4 Matrix:
 [[-2.50919762  9.01428613  4.63987884  1.97316968]
 [-6.87962719 -6.88010959 -8.83832776  7.32352292]
 [ 2.02230023  4.16145156 -9.58831011  9.39819704]]


In [ ]:
# Basic Statistics
print("--- Basic Statistics ---")
max_val = np.max(matrix_3x4)
min_val = np.min(matrix_3x4)
argmax_flat = np.argmax(matrix_3x4)
argmin_flat = np.argmin(matrix_3x4)
argmax_2d = np.unravel_index(argmax_flat, matrix_3x4.shape)
argmin_2d = np.unravel_index(argmin_flat, matrix_3x4.shape)

print(f"Maximum Value: {max_val:.4f}")
print(f"Minimum Value: {min_val:.4f}")
print(f"Index Position of Max Value (Flat Index: {argmax_flat}, 2D Index: {argmax_2d})")
print(f"Index Position of Min Value (Flat Index: {argmin_flat}, 2D Index: {argmin_2d})")
print(f"Sum of All Elements: {np.sum(matrix_3x4):.4f}")
print(f"Product of All Elements: {np.prod(matrix_3x4):.4e}")
print(f"Mean: {np.mean(matrix_3x4):.4f}")
print(f"Median: {np.median(matrix_3x4):.4f}")
print(f"Variance: {np.var(matrix_3x4):.4f}")
print(f"Standard Deviation: {np.std(matrix_3x4):.4f}")


--- Basic Statistics ---
Maximum Value: 9.3982
Minimum Value: -9.5883
Index Position of Max Value (Flat Index: 11, 2D Index: (np.int64(2), np.int64(3)))
Index Position of Min Value (Flat Index: 10, 2D Index: (np.int64(2), np.int64(2)))
Sum of All Elements: 3.8372
Product of All Elements: -4.8113e+08
Mean: 0.3198
Median: 1.9977
Variance: 44.9861
Standard Deviation: 6.7072


In [ ]:
# Row and Column Analysis
print("--- Row and Column Analysis ---")
row_sum = np.sum(matrix_3x4, axis=1)
col_sum = np.sum(matrix_3x4, axis=0)
row_max = np.max(matrix_3x4, axis=1)
col_min = np.min(matrix_3x4, axis=0)

print("Sum of each row (axis=1):\n", row_sum)
print("\nSum of each column (axis=0):\n", col_sum)
print("\nMaximum value from each row (axis=1):\n", row_max)
print("\nMinimum value from each column (axis=0):\n", col_min)


--- Row and Column Analysis ---
Sum of each row (axis=1):
 [ 13.11813703 -15.27454163   5.99363872]

Sum of each column (axis=0):
 [ -7.36652458   6.29562809 -13.78675903  18.69488964]

Maximum value from each row (axis=1):
 [9.01428613 7.32352292 9.39819704]

Minimum value from each column (axis=0):
 [-6.87962719 -6.88010959 -9.58831011  1.97316968]


---
## 4. Matrix Sorting and Searching Operations


In [ ]:
# Create a 4x4 integer matrix using random values
np.random.seed(101)
matrix_4x4 = np.random.randint(-20, 20, (4, 4))

print("Original 4x4 Integer Matrix:\n", matrix_4x4)


Original 4x4 Integer Matrix:
 [[ 11  -9  -3 -14]
 [  3  -9 -11  -7]
 [-16   8 -20 -15]
 [ -8   9  -1 -12]]


In [ ]:
# Sorting Operations
print("--- Sorting Operations ---")
# 1. Sort each row in ascending order
row_asc = np.sort(matrix_4x4, axis=1)
print("1. Sort each row in ascending order:\n", row_asc)

# 2. Sort each row in descending order
row_desc = np.sort(matrix_4x4, axis=1)[:, ::-1]
print("\n2. Sort each row in descending order:\n", row_desc)

# 3. Sort entire matrix in ascending order
flat_asc = np.sort(matrix_4x4.flatten())
matrix_asc = flat_asc.reshape(4, 4)
print("\n3. Sort entire matrix in ascending order (reshaped 4x4):\n", matrix_asc)

# 4. Sort entire matrix in descending order
flat_desc = flat_asc[::-1]
matrix_desc = flat_desc.reshape(4, 4)
print("\n4. Sort entire matrix in descending order (reshaped 4x4):\n", matrix_desc)


--- Sorting Operations ---
1. Sort each row in ascending order:
 [[-14  -9  -3  11]
 [-11  -9  -7   3]
 [-20 -16 -15   8]
 [-12  -8  -1   9]]

2. Sort each row in descending order:
 [[ 11  -3  -9 -14]
 [  3  -7  -9 -11]
 [  8 -15 -16 -20]
 [  9  -1  -8 -12]]

3. Sort entire matrix in ascending order (reshaped 4x4):
 [[-20 -16 -15 -14]
 [-12 -11  -9  -9]
 [ -8  -7  -3  -1]
 [  3   8   9  11]]

4. Sort entire matrix in descending order (reshaped 4x4):
 [[ 11   9   8   3]
 [ -1  -3  -7  -8]
 [ -9  -9 -11 -12]
 [-14 -15 -16 -20]]


In [ ]:
print("--- Finding Elements ---")
matrix_flat = matrix_4x4.flatten()

# 5 largest and 5 smallest values
five_largest = np.sort(matrix_flat)[-5:][::-1]
five_smallest = np.sort(matrix_flat)[:5]

print("Five largest values in matrix:", five_largest)
print("Five smallest values in matrix:", five_smallest)

# mean
mat_mean = matrix_4x4.mean()
print(f"Matrix Mean: {mat_mean:.4f}")

#position
pos_gt_mean = np.argwhere(matrix_4x4 > mat_mean)
print("Positions (Row, Col) of elements greater than mean:\n", pos_gt_mean)

# counts of positive, negative, and zero values
pos_count = np.sum(matrix_4x4 > 0)
neg_count = np.sum(matrix_4x4 < 0)
zero_count = np.sum(matrix_4x4 == 0)

print(f"Count of positive values (>0): {pos_count}")
print(f"Count of negative values (<0): {neg_count}")
print(f"Count of zero values (==0): {zero_count}")


--- Finding Elements ---
Five largest values in matrix: [11  9  8  3 -1]
Five smallest values in matrix: [-20 -16 -15 -14 -12]
Matrix Mean: -5.8750
Positions (Row, Col) of elements greater than mean:
 [[0 0]
 [0 2]
 [1 0]
 [2 1]
 [3 1]
 [3 2]]
Count of positive values (>0): 4
Count of negative values (<0): 12
Count of zero values (==0): 0
